/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bloodbankmanagementsystem;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class ListOfAll extends javax.swing.JFrame {

    /**
     * Creates new form ListOfAll
     */
    int Quantity;
    public ListOfAll() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        P_dashboard = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        userOption = new javax.swing.JComboBox<>();
        A_list = new javax.swing.JButton();
        A_requestD = new javax.swing.JButton();
        A_requestP = new javax.swing.JButton();
        ShowList = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        P_dashboard.setBackground(new java.awt.Color(0, 84, 180));
        P_dashboard.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        P_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        P_dashboard.setText("Dashboard");
        P_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        P_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                P_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                P_dashboardMouseExited(evt);
            }
        });
        P_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_dashboardActionPerformed(evt);
            }
        });

        listTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Gender", "Blood Group", "Date of Birth", "Address", "Email", "Phone NO."
            }
        ));
        jScrollPane2.setViewportView(listTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        userOption.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        userOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Donor", "Patient" }));

        A_list.setBackground(new java.awt.Color(0, 153, 153));
        A_list.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        A_list.setForeground(new java.awt.Color(255, 255, 255));
        A_list.setText("List");
        A_list.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        A_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                A_listMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                A_listMouseExited(evt);
            }
        });
        A_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_listActionPerformed(evt);
            }
        });

        A_requestD.setBackground(new java.awt.Color(0, 84, 180));
        A_requestD.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        A_requestD.setForeground(new java.awt.Color(255, 255, 255));
        A_requestD.setText("Donor Request");
        A_requestD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        A_requestD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                A_requestDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                A_requestDMouseExited(evt);
            }
        });
        A_requestD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_requestDActionPerformed(evt);
            }
        });

        A_requestP.setBackground(new java.awt.Color(0, 84, 180));
        A_requestP.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        A_requestP.setForeground(new java.awt.Color(255, 255, 255));
        A_requestP.setText("Patient Request");
        A_requestP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        A_requestP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                A_requestPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                A_requestPMouseExited(evt);
            }
        });
        A_requestP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_requestPActionPerformed(evt);
            }
        });

        ShowList.setBackground(new java.awt.Color(0, 84, 180));
        ShowList.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ShowList.setForeground(new java.awt.Color(255, 255, 255));
        ShowList.setText("Show List");
        ShowList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(P_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(A_list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(A_requestD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(A_requestP, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(userOption, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(ShowList, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ShowList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userOption, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(P_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(A_list, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(A_requestD, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(A_requestP, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Management System");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Blood Bank");

        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setText(" X");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });

        minimize.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        minimize.setText(" -");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(minimize)
                        .addComponent(close)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void P_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_dashboardMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_P_dashboardMouseEntered

    private void P_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_dashboardMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_P_dashboardMouseExited

    private void P_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_dashboardActionPerformed
        adminDashboard adb = new adminDashboard();
        adb.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_P_dashboardActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        Border lebel_border = BorderFactory.createMatteBorder(2,2,2,2, Color.white);
        close.setBorder(lebel_border);
        close.setForeground(Color.white);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        Border lebel_border = BorderFactory.createMatteBorder(2,2,2,2, Color.black);
        close.setBorder(lebel_border);
        close.setForeground(Color.black);
    }//GEN-LAST:event_closeMouseExited

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        Border lebel_border = BorderFactory.createMatteBorder(2,2,2,2, Color.white);
        minimize.setBorder(lebel_border);
        minimize.setForeground(Color.white);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        Border lebel_border = BorderFactory.createMatteBorder(2,2,2,2, Color.black);
        minimize.setBorder(lebel_border);
        minimize.setForeground(Color.BLACK);
    }//GEN-LAST:event_minimizeMouseExited

    private void A_listMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_listMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_A_listMouseEntered

    private void A_listMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_listMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_A_listMouseExited

    private void A_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_listActionPerformed
        ListOfAll loa = new ListOfAll();
        loa.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_A_listActionPerformed

    private void A_requestDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_requestDMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_A_requestDMouseEntered

    private void A_requestDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_requestDMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_A_requestDMouseExited

    private void A_requestDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_requestDActionPerformed
        RequestOfDonor rod = new RequestOfDonor();
        rod.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_A_requestDActionPerformed

    private void A_requestPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_requestPMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_A_requestPMouseEntered

    private void A_requestPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A_requestPMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_A_requestPMouseExited

    private void A_requestPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_requestPActionPerformed
        RequestOfPatient rop = new RequestOfPatient();
        rop.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_A_requestPActionPerformed

    private void ShowListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowListActionPerformed
        String option = userOption.getSelectedItem().toString();
        if(option.equals("Donor")){
        PreparedStatement ps;
        ResultSet rs;
        String showQuery = "SELECT `name`, `gender`, `blood_group`, `Date of Birth`, `address`, `email`, `phone_number` FROM `donor_db`;";
        try {
            ps = MySqlConnection.getConnection().prepareStatement(showQuery);
            rs = ps.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            DefaultTableModel model = (DefaultTableModel) listTable.getModel();
            int cols = rsmd.getColumnCount();
            model.setRowCount(0);
            while(rs.next()){
            Vector v = new Vector();
            for(int i=0; i<cols;i++){
                v.add(rs.getString("name"));
                v.add(rs.getString("gender"));
                v.add(rs.getString("blood_group"));
                v.add(rs.getString("Date of Birth"));
                v.add(rs.getString("address"));
                v.add(rs.getString("email"));
                v.add(rs.getString("phone_number"));
            }
             model.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DonorDonateList.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else if(option.equals("Patient")){
            PreparedStatement ps;
        ResultSet rs;
        String showQuery = "SELECT `name`, `gender`, `blood_group`, `Date of Birth`, `address`, `email`, `phone_number` FROM `patient_db`;";
        try {
            ps = MySqlConnection.getConnection().prepareStatement(showQuery);
            rs = ps.executeQuery();
            ResultSetMetaData rsmd = rs.getMetaData();
            DefaultTableModel model = (DefaultTableModel) listTable.getModel();
            int cols = rsmd.getColumnCount();
            model.setRowCount(0);
            while(rs.next()){
            Vector v = new Vector();
            for(int i=0; i<cols;i++){
                v.add(rs.getString("name"));
                v.add(rs.getString("gender"));
                v.add(rs.getString("blood_group"));
                v.add(rs.getString("Date of Birth"));
                v.add(rs.getString("address"));
                v.add(rs.getString("email"));
                v.add(rs.getString("phone_number"));
            }
             model.addRow(v);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DonorDonateList.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_ShowListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListOfAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListOfAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListOfAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListOfAll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListOfAll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_list;
    private javax.swing.JButton A_requestD;
    private javax.swing.JButton A_requestP;
    private javax.swing.JButton P_dashboard;
    private javax.swing.JButton ShowList;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable listTable;
    private javax.swing.JLabel minimize;
    private javax.swing.JComboBox<String> userOption;
    // End of variables declaration//GEN-END:variables
}
